# copied from https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/v3.0.1/deploy/kubernetes/class.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs
provisioner: example.com/nfs
mountOptions:
  - vers=4.1
