---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: stor-system

resources:
  - github.com/rancher/local-path-provisioner/deploy?ref=v0.0.21

patchesStrategicMerge:
  - configmap.yaml  # to change default path of dir on node
  - deployment.yaml # to add node selector
