---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
